/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#715b3e",
        "surface-container-high": "#ebe8e3",
        "error-container": "#ffdad6",
        "tertiary-container": "#b9b2aa",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "on-background": "#1c1c19",
        "on-primary-container": "#554227",
        "on-secondary-container": "#73640e",
        "on-error-container": "#93000a",
        "inverse-surface": "#31302d",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#e5e2dd",
        "secondary-container": "#f7e382",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#e9e1d9",
        "on-primary-fixed-variant": "#574329",
        "primary-fixed": "#fcdeba",
        tertiary: "#635e57",
        "on-primary-fixed": "#281903",
        "surface-container": "#f0ede8",
        background: "#fcf9f4",
        "surface-tint": "#715b3e",
        "secondary-fixed": "#f7e382",
        "on-surface": "#1c1c19",
        "inverse-primary": "#dfc29f",
        "surface-bright": "#fcf9f4",
        "on-tertiary-fixed-variant": "#4b4640",
        outline: "#7f7663",
        "surface-dim": "#dcdad5",
        "on-tertiary-container": "#49443f",
        "primary-container": "#caae8d",
        "on-secondary-fixed-variant": "#524700",
        surface: "#fcf9f4",
        "outline-variant": "#d0c5af",
        error: "#ba1a1a",
        "secondary-fixed-dim": "#dac769",
        "on-tertiary-fixed": "#1e1b16",
        "on-secondary-fixed": "#211b00",
        "on-primary": "#ffffff",
        "surface-container-low": "#f6f3ee",
        "inverse-on-surface": "#f3f0eb",
        secondary: "#6c5e06",
        "on-surface-variant": "#4d4635",
        "tertiary-fixed-dim": "#cdc5bd",
        "primary-fixed-dim": "#dfc29f",
        "surface-variant": "#e5e2dd",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Noto Serif"],
        body: ["Manrope"],
        label: ["Manrope"],
      },
    },
  },
  plugins: [],
};